CREATE TABLE library.users (
    id INT AUTO_INCREMENT NOT NULL,
    user VARCHAR(50) NOT NULL,
    pass VARCHAR(255) NOT NULL,
    nickname VARCHAR(50) NOT NULL,
    create_date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
)
