CREATE TABLE library.series (
    id INT AUTO_INCREMENT NOT NULL,
    user_id INT NOT NULL,
    series_name VARCHAR(50),
    create_date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
)